# Generated by Django 5.2.10 on 2026-01-23 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('disciplinas', '0002_combo'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno', 'disciplina')},
        ),
        migrations.AddField(
            model_name='pago',
            name='relacion_inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.inscripcion'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('MERCADO_PAGO', 'Mercado Pago'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(condition=models.Q(('horario__isnull', False)), fields=('alumno', 'horario'), name='unique_alumno_horario'),
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='descuento_manual',
        ),
    ]
