# Generated by Django 5.2.10 on 2026-02-16 17:39

import alumnos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=alumnos.models.Alumno.foto_path),
        ),
    ]
