# Generated by Django 5.2.10 on 2026-01-23 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('MMA', 'MMA'), ('LUTA_LIVRE', 'Luta Livre'), ('JIU_JITSU', 'Jiu Jitsu'), ('MUAY_THAI', 'Muay Thai'), ('KICKBOXING', 'Kickboxing'), ('PARKOUR', 'Parkour'), ('WRESTLING', 'Wrestling'), ('BOXEO', 'Boxeo'), ('FUNCIONAL', 'Funcional'), ('ESTA', 'Esta')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_clase_suelta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('capacidad_maxima', models.PositiveIntegerField(default=20)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='disciplinas.disciplina')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('disciplina', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
