# Generated by Django 5.2.10 on 2026-01-24 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
