# Generated by Django 6.0 on 2026-04-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0003_disciplina_activa_disciplina_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nombre',
            field=models.CharField(choices=[('MMA', 'MMA'), ('LUTA_LIVRE', 'Luta Livre'), ('JIU_JITSU', 'Jiu Jitsu'), ('MUAY_THAI', 'Muay Thai'), ('KICKBOXING', 'Kickboxing'), ('PARKOUR', 'Parkour'), ('WRESTLING', 'Wrestling'), ('BOXEO', 'Boxeo'), ('FUNCIONAL', 'Funcional'), ('INFANTILES', 'Infantiles')], max_length=20, unique=True),
        ),
    ]
